---
# Autoflow Community — Receptor (nœud local unique, sans mesh)

- node:
    id: awx
    datadir: /var/lib/receptor

- local-only: {}

- log-level:
    level: info

- control-service:
    service: control
    filename: /var/run/receptor/receptor.sock

- work-command:
    worktype: local
    command: ansible-runner
    params: worker
    allowruntimeparams: true
